### ISSUE TITLE
Bug when trying to play video

### ISSUE THREAD

**Issue by tye-exe** [DarkSavci/Minecraft-Video-Player#1]
When I do "/processvideo https://www.youtube.com/watch?v=dQw4w9WgXcQ" It errors.
See attached file for error log.
The minecraft server is 1.19.4 paper.

[error.txt](https://github.com/DarkSavci/Minecraft-Video-Player/files/11742060/error.txt)

...

As it turns out you have to link a video file directly, you can't just use a youtube url

**Comment by DarkSavci** [comment]
Hello you should put a link that directly gets a video. So youtube links  won't work. Fo ex: [https://example.com/**video.mp4**](). If you don't know how these work you can just send a video in discord then copy link from discord that way you can get a working link.

**Comment by Timoti11** [comment]
+, it's not working.
Links for use:
- `https://www.dropbox.com/s/feprv6kfg7qhbm1/2023-01-28-04-24-22.mov`
- `https://i.imgur.com/9oftCVX.jpg`
- `https://www.dropbox.com/s/6koac729621sgdi/2023-04-04%2023-01-06.mp4`

Purpur 1.19.4

**Comment by DarkSavci** [comment]
Your links contains the same issue. Your address does not directly gets the video. It gets an HTML file that links to your video. Here is a [address](https://cdn.stylsheets.com/badapple.mp4) for reference. But I can confirm that plugins bugs out when using wrong addresses.
